name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t azkadevops/nodejs:latest .
      - name: push Docker Image
        run: |
          docker login --username azkadevops --password a01m132806
          docker push azkadevops/nodejs:latest
