name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t azkadevops/nodejs:1.1 .
          docker login --username azkadevops --password a01m132806
          docker push azkadevops/nodejs:1.1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:      
      - name: Setup SSH
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@18.206.76.64

      - name: Run container
        run: | 
          docker login --username azkadevops --password a01m132806
          docker compose up -d
